version: "3.9"

networks:
  students:
    driver: bridge

services:
  db:
    container_name: mysql5.7
    image: mysql:5.7.22
    restart: always
    environment:
      MYSQL_DATABASE: students
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./.docker/mysql:/var/lib/mysql
    ports:
      - 33066:3306
    networks:
      - students

  phpmyadmin:
    container_name: phpmyadmin
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 9002:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    networks:
      - students
